{% set version = "0.14.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-precrec
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/precrec_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/precrec/precrec_{{ version }}.tar.gz
  sha256: a81be3001ad25ff8d2dfff29390a08008875e0b4e4a8e398e37f8d4b18c7fe12

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.2
    - r-assertthat >=0.1
    - r-data.table >=1.10.4
    - r-ggplot2 >=2.1.0
    - r-gridextra >=2.0.0
    - r-withr >=2.3.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.2
    - r-assertthat >=0.1
    - r-data.table >=1.10.4
    - r-ggplot2 >=2.1.0
    - r-gridextra >=2.0.0
    - r-withr >=2.3.0

test:
  commands:
    - $R -e "library('precrec')"           # [not win]
    - "\"%R%\" -e \"library('precrec')\""  # [win]

about:
  home: http://takayasaito.github.io/precrec, https://github.com/takayasaito/precrec
  license: GPL-3.0-only
  summary: Accurate calculations and visualization of precision-recall and ROC (Receiver Operator Characteristics) curves.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: precrec
# Type: Package
# Title: Calculate Accurate Precision-Recall and ROC (Receiver Operator Characteristics) Curves
# Version: 0.10.1
# Date: 2019-04-12
# Authors@R: c( person("Takaya", "Saito", email = "takaya.saito@outlook.com", role = c("aut", "cre")), person("Marc", "Rehmsmeier", email = "marc.rehmsmeier@ii.uib.no", role = c("aut")))
# Description: Accurate calculations and visualization of precision-recall and ROC (Receiver Operator Characteristics) curves.
# URL: http://takayasaito.github.io/precrec, https://github.com/takayasaito/precrec
# BugReports: https://github.com/takayasaito/precrec/issues
# Depends: R (>= 3.2.1)
# License: GPL-3
# LazyData: TRUE
# Suggests: testthat (>= 0.11.0), knitr (>= 1.11), rmarkdown (>= 0.8.1)
# LinkingTo: Rcpp
# Imports: Rcpp (>= 0.12.2), ggplot2 (>= 2.1.0), assertthat (>= 0.1), grid, gridExtra (>= 2.0.0), methods, data.table (>= 1.10.4)
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-04-12 19:51:43 UTC; a21379
# Author: Takaya Saito [aut, cre], Marc Rehmsmeier [aut]
# Maintainer: Takaya Saito <takaya.saito@outlook.com>
# Repository: CRAN
# Date/Publication: 2019-04-12 20:23:45 UTC
