travis:
  secure:
    BINSTAR_TOKEN: DjmaPB+Bpe7gS4iJzTpaa334p1v18ZOKQZsG1rYVH5qDQukq8x4n6veu9dEpUoo2eVszatEi9oru5g3udpgsw59hD/TjzmZq3w4VX56laQKaYky9n8AO82WxUU7XVvmVqQGxq6h6vEaapxAc0ulGDDntwsb9afTbMoT+P4cIl4EVmGRs1XdM4UQMF+MlQlBUciong/eyMDi6ZGdi7eAxcmvfWNzQ09xeIXOvAsymX3iXMHa70EOrxRE8Kpg1kr4DmcsbJCzrat1CYQhEl6HMVci3RhNwPFszp3Auh9QOdREhdSit5WG6jG13yMH+NkKy8t4rI2UALsvevWQq4mrMEy4sp6SvYSMibMFaHDsCfIZxb7bEAkgzWjFSw8o4SKoFw/bfzuP/mTKtGA5UYS6gwb8nhtboM/4mGfdEBHtyAtrtqFvSLBNFJenozStpC9qCeRrQ2ZDduJ5p7lG+Qu29MgDHQwCphAfVEHdgG02L3naNozjXyrN7LehejwCyAbASFSJcEDEoR9q1tG1UOLnjINEDdXMj39xG3zAG78TyhGOAisoJJYzrSwexnNEYk3C4chLFP7RLQCL277YH5DxMoK9QQOVgkgfubwhIpxoZzW42Y3+LK96s8/v1NPqDz+jVoumKZEAAr/Qc9R2j6QMsKu09sJt3rypqbIQEl8L8fuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
