travis:
  secure:
    BINSTAR_TOKEN: m01UKld4P4roKhPDaTA3N2coFVpwkKgDtvXtZ40lKZerJ1icfCvHFKPMZJzz2jH35iuWFu0QcNM77Y6LpjVJhyaIsX97KwdY0I4nEfWaPX4obdmTmQFbjDHlDjHnZjb0GVwLNCf0Lw2MXYf0QC7nnjHN8dWp7bUQfVAiYow9osnKueCFKf4BxsfXRriG7vgR2HWlTOhBA+GNauxE6LWxMsL5arL+OYaQgaIW81mFBUUNhcXVsLmYNh5hbkxYqCh4PAsBWkfRNASQQCkhpMsrgf4K2qHGiwMurkRampZRZLiMFbyaw9/c3ghQpId+pBHd9cMmUrH7e/iYfVsvFHxOwb4ktrOZF/u7kkdJ/S1tlDeUizAPRhc69E3uZ3jLBupBbOLEUC/QJ7Wd+YVNMPd9UwW/RcWgD0myXkta615P4xDMrFkbYb/Y7Q3hDhukzsX2zBcd988jFU58dSpkszhmPylUjdxa39zXbUuAkCaMKCCnfQRipsb1zokB043t5yCp2Jhzu7O1DmRfcEfkYhfKeA/xHvWRNJDp4TiWLxBPcgDMWl6n40vOG4+Fgt/XUHWeVBXG9mYMeSNABHfugjyq7LUgwen3OD7U3rJ52BOxcMQLLpYyRB5akQYoYFr7Zr2ulTE7iLd+/Fx6kHXQALSJnZQHeOZ0B2R5RIlw/Pq1o8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
