travis:
  secure:
    BINSTAR_TOKEN: g7NfjjkjL+JNSlGzcxx2HdKIMf63HuV9CpspM5YfI2tQMNewR40F1VPFeKbhI+ncM4dqSuycKDcGQHtq6kQHmw9garqYnhm82ndzmj77THe/eMjJYlAlqI5isUF9uPlDQoRcYWQ1fWeRAiMe+G9oqpReantOPEULE+3vEyYgaBn6DpSfKbpbtyNDQf0pNtmn1REvzSLzvzfmYdmhcIheVsdU0Kj6m1EGQPgZaKFd7cp+PvukJ4Tgnk3S+IkxKKTRxLcan/U0Qc8cXFPYSL6Tkq5KkY3Dz+3T5V0k5vh8qa6LP4yoF8ZVfBs4zsbb3HBNLtHunPUlfCqJVKs3hiZiWlAcyeEKEVPWl38yrWGJ5bD6XCp1jFdZYdIZU9kFEJcqF+y7/oCNJWG2WOgEQ7wdX3weDZliHYkPxJSFgJxgVHS0f8/EJbHQM5hjCC6jU6hSBNbH+ae3pTwwFA4VVvqXmLZC3XI8EhHwfycVDkEWaF8ILjFE5qF9LglYo1H6xbt8lhggS2kz8vIfy58wzffbI3nhyN8V4wrinRQ3E5AFuHZKARgb+wCi9NVK/c99wWeDoGTdyPK3NUN9nUQ4ywpE5OKNN9xKGFlglVzcSUo4SvzkDTn/EIDe1tphM4eHAn8FsZK0U4SNhekZN8S6EbTtMk+iUec9Q8yNghDha6hHwm0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
